version: '3.8'

# ${DOCKER_LOCAL} is an environment variable on the host. It contains the absoulte path of folder. 
#                 This is the base folder for all docker related files stored outside of the VM.

services:

    # https://jfrog.com/open-source/#artifactory
    #
    # Local repository for build artifacts.
    # Port range: 11000-11009
    artifactory:
        container_name: artifactory
        image: docker.bintray.io/jfrog/artifactory-oss:7.7.3
        ports:
            - 11001:8081
            - 11002:8082
        volumes:
            - artifactory-data:/var/opt/jfrog/artifactory
        restart: always
        logging:
            driver: json-file
            options:
                max-size: "50m"
                max-file: "10"
        ulimits:
            nproc: 65535
            nofile:
                soft: 32000
                hard: 40000
    
    # https://www.jenkins.io/
    #
    # Build and deployment automation tool. Mostly for learning how it works.
    # Port range: 11010-11019
    jenkins:
        container_name: jenkins
        image: jenkins/jenkins:lts
        ports:
            - 11010:8080
        volumes:
            - jenkins-data:/var/jenkins_home
        restart: always
    
    # https://structurizr.com/
    #
    # Software system design tool.
    # Port range: 11020-11029
    structurizr:
        container_name: structurizr
        build:
            context: ./structurizr
            args:
                - STRUCTURIZR_BUILD=2094
                - STRUCTURIZR_LICENSE_FILE=${DOCKER_LOCAL}/config/devops/structurizr/structurizr.properties
        ports:
            - 11020:8080
        environment:
            - STRUCTURIZR_PLANTUML=http://plantuml.com/plantuml
            - STRUCTURIZR_GRAPHVIZ=true
        volumes:
            - structurizr-data:/usr/local/structurizr
        restart: always
    
    # https://www.postgresql.org/
    #
    # Dummy database for quick prototyping.
    # Port range: 11030-11039
    postgres:
        container_name: postgres
        image: postgres:13-alpine
        ports:
            - 11032:5432
        env_file:
            - ${DOCKER_LOCAL}/env/devops/postgres/postgres.env
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: always

volumes:
    artifactory-data:
    jenkins-data:
    structurizr-data:
    postgres-data:
